;;;; package.lisp

(defpackage #:cl-bgfx
  (:use #:cl)
  (:export
   :+bgfx-api-version+ 
   :+bgfx-buffer-allow-resize+ 
   :+bgfx-buffer-compute-format-16x1+ 
   :+bgfx-buffer-compute-format-16x2+ 
   :+bgfx-buffer-compute-format-16x4+ 
   :+bgfx-buffer-compute-format-32x1+ 
   :+bgfx-buffer-compute-format-32x2+ 
   :+bgfx-buffer-compute-format-32x4+ 
   :+bgfx-buffer-compute-format-8x1+ 
   :+bgfx-buffer-compute-format-8x2+ 
   :+bgfx-buffer-compute-format-8x4+ 
   :+bgfx-buffer-compute-format-mask+ 
   :+bgfx-buffer-compute-format-shift+ 
   :+bgfx-buffer-compute-read+ 
   :+bgfx-buffer-compute-read-write+ 
   :+bgfx-buffer-compute-type-float+ 
   :+bgfx-buffer-compute-type-int+ 
   :+bgfx-buffer-compute-type-mask+ 
   :+bgfx-buffer-compute-type-shift+ 
   :+bgfx-buffer-compute-type-uint+ 
   :+bgfx-buffer-compute-write+ 
   :+bgfx-buffer-draw-indirect+ 
   :+bgfx-buffer-index32+ 
   :+bgfx-buffer-none+ 
   :+bgfx-caps-alpha-to-coverage+ 
   :+bgfx-caps-blend-independent+ 
   :+bgfx-caps-compute+ 
   :+bgfx-caps-conservative-raster+ 
   :+bgfx-caps-draw-indirect+ 
   :+bgfx-caps-format-texture-2d+ 
   :+bgfx-caps-format-texture-2d-emulated+ 
   :+bgfx-caps-format-texture-2d-srgb+ 
   :+bgfx-caps-format-texture-3d+ 
   :+bgfx-caps-format-texture-3d-emulated+ 
   :+bgfx-caps-format-texture-3d-srgb+ 
   :+bgfx-caps-format-texture-cube+ 
   :+bgfx-caps-format-texture-cube-emulated+ 
   :+bgfx-caps-format-texture-cube-srgb+ 
   :+bgfx-caps-format-texture-framebuffer+ 
   :+bgfx-caps-format-texture-framebuffer-msaa+ 
   :+bgfx-caps-format-texture-image+ 
   :+bgfx-caps-format-texture-mip-autogen+ 
   :+bgfx-caps-format-texture-msaa+ 
   :+bgfx-caps-format-texture-none+ 
   :+bgfx-caps-format-texture-vertex+ 
   :+bgfx-caps-fragment-depth+ 
   :+bgfx-caps-fragment-ordering+ 
   :+bgfx-caps-graphics-debugger+ 
   :+bgfx-caps-hidpi+ 
   :+bgfx-caps-index32+ 
   :+bgfx-caps-instancing+ 
   :+bgfx-caps-occlusion-query+ 
   :+bgfx-caps-renderer-multithreaded+ 
   :+bgfx-caps-swap-chain+ 
   :+bgfx-caps-texture-2d-array+ 
   :+bgfx-caps-texture-3d+ 
   :+bgfx-caps-texture-blit+ 
   :+bgfx-caps-texture-compare-all+ 
   :+bgfx-caps-texture-compare-lequal+ 
   :+bgfx-caps-texture-cube-array+ 
   :+bgfx-caps-texture-direct-access+ 
   :+bgfx-caps-texture-read-back+ 
   :+bgfx-caps-vertex-attrib-half+ 
   :+bgfx-caps-vertex-attrib-uint10+ 
   :+bgfx-caps-vertex-id+ 
   :+bgfx-clear-color+ 
   :+bgfx-clear-depth+ 
   :+bgfx-clear-discard-color-0+ 
   :+bgfx-clear-discard-color-1+ 
   :+bgfx-clear-discard-color-2+ 
   :+bgfx-clear-discard-color-3+ 
   :+bgfx-clear-discard-color-4+ 
   :+bgfx-clear-discard-color-5+ 
   :+bgfx-clear-discard-color-6+ 
   :+bgfx-clear-discard-color-7+ 
   :+bgfx-clear-discard-color-mask+ 
   :+bgfx-clear-discard-depth+ 
   :+bgfx-clear-discard-mask 
   :+bgfx-clear-discard-stencil+ 
   :+bgfx-clear-none+ 
   :+bgfx-clear-stencil+ 
   :+bgfx-cube-map-negative-x+ 
   :+bgfx-cube-map-negative-y+ 
   :+bgfx-cube-map-negative-z+ 
   :+bgfx-cube-map-positive-x+ 
   :+bgfx-cube-map-positive-y+ 
   :+bgfx-cube-map-positive-z+ 
   :+bgfx-debug-ifh+ 
   :+bgfx-debug-none+ 
   :+bgfx-debug-profiler+ 
   :+bgfx-debug-stats+ 
   :+bgfx-debug-text+ 
   :+bgfx-debug-wireframe+ 
   :+bgfx-pci-id-amd+ 
   :+bgfx-pci-id-intel+ 
   :+bgfx-pci-id-none+ 
   :+bgfx-pci-id-nvidia+ 
   :+bgfx-pci-id-software-rasterizer+ 
   :+bgfx-reset-capture+ 
   :+bgfx-reset-depth-clamp+ 
   :+bgfx-reset-flip-after-render+ 
   :+bgfx-reset-flush-after-render+ 
   :+bgfx-reset-fullscreen+ 
   :+bgfx-reset-fullscreen-mask+ 
   :+bgfx-reset-fullscreen-shift+ 
   :+bgfx-reset-hidpi+ 
   :+bgfx-reset-maxanisotropy+ 
   :+bgfx-reset-msaa-mask+ 
   :+bgfx-reset-msaa-shift+ 
   :+bgfx-reset-msaa-x16+ 
   :+bgfx-reset-msaa-x2+ 
   :+bgfx-reset-msaa-x4+ 
   :+bgfx-reset-msaa-x8+ 
   :+bgfx-reset-none+ 
   :+bgfx-reset-reserved-mask+ 
   :+bgfx-reset-reserved-shift+ 
   :+bgfx-reset-srgb-backbuffer+ 
   :+bgfx-reset-suspend+ 
   :+bgfx-reset-vsync+ 
   :+bgfx-state-alpha-ref-mask+ 
   :+bgfx-state-alpha-ref-shift+ 
   :+bgfx-state-blend-alpha-to-coverage+ 
   :+bgfx-state-blend-dst-alpha+ 
   :+bgfx-state-blend-dst-color+ 
   :+bgfx-state-blend-equation-add+ 
   :+bgfx-state-blend-equation-mask+ 
   :+bgfx-state-blend-equation-max+ 
   :+bgfx-state-blend-equation-min+ 
   :+bgfx-state-blend-equation-revsub+ 
   :+bgfx-state-blend-equation-shift+ 
   :+bgfx-state-blend-equation-sub+ 
   :+bgfx-state-blend-factor+ 
   :+bgfx-state-blend-independent+ 
   :+bgfx-state-blend-inv-dst-alpha+ 
   :+bgfx-state-blend-inv-dst-color+ 
   :+bgfx-state-blend-inv-factor+ 
   :+bgfx-state-blend-inv-src-alpha+ 
   :+bgfx-state-blend-inv-src-color+ 
   :+bgfx-state-blend-mask+ 
   :+bgfx-state-blend-one+ 
   :+bgfx-state-blend-shift+ 
   :+bgfx-state-blend-src-alpha+ 
   :+bgfx-state-blend-src-alpha-sat+ 
   :+bgfx-state-blend-src-color+ 
   :+bgfx-state-blend-zero+ 
   :+bgfx-state-conservative-raster+ 
   :+bgfx-state-cull-ccw+ 
   :+bgfx-state-cull-cw+ 
   :+bgfx-state-cull-mask+ 
   :+bgfx-state-cull-shift+ 
   :+bgfx-state-default+ 
   :+bgfx-state-depth-test-always+ 
   :+bgfx-state-depth-test-equal+ 
   :+bgfx-state-depth-test-gequal+ 
   :+bgfx-state-depth-test-greater+ 
   :+bgfx-state-depth-test-lequal+ 
   :+bgfx-state-depth-test-less+ 
   :+bgfx-state-depth-test-mask+ 
   :+bgfx-state-depth-test-never+ 
   :+bgfx-state-depth-test-notequal+ 
   :+bgfx-state-depth-test-shift+ 
   :+bgfx-state-lineaa+ 
   :+bgfx-state-mask+ 
   :+bgfx-state-msaa+ 
   :+bgfx-state-none+ 
   :+bgfx-state-point-size-mask+ 
   :+bgfx-state-point-size-shift+ 
   :+bgfx-state-pt-lines+ 
   :+bgfx-state-pt-linestrip+ 
   :+bgfx-state-pt-mask+ 
   :+bgfx-state-pt-points+ 
   :+bgfx-state-pt-shift+ 
   :+bgfx-state-pt-tristrip+ 
   :+bgfx-state-reserved-mask+ 
   :+bgfx-state-reserved-shift+ 
   :+bgfx-state-write-a+ 
   :+bgfx-state-write-b+ 
   :+bgfx-state-write-g+ 
   :+bgfx-state-write-mask+ 
   :+bgfx-state-write-r+ 
   :+bgfx-state-write-rgb+ 
   :+bgfx-state-write-z+ 
   :+bgfx-stencil-default+ 
   :+bgfx-stencil-func-ref-mask+ 
   :+bgfx-stencil-func-ref-shift+ 
   :+bgfx-stencil-func-rmask-mask+ 
   :+bgfx-stencil-func-rmask-shift+ 
   :+bgfx-stencil-mask+ 
   :+bgfx-stencil-none+ 
   :+bgfx-stencil-op-fail-s-decr+ 
   :+bgfx-stencil-op-fail-s-decrsat+ 
   :+bgfx-stencil-op-fail-s-incr+ 
   :+bgfx-stencil-op-fail-s-incrsat+ 
   :+bgfx-stencil-op-fail-s-invert+ 
   :+bgfx-stencil-op-fail-s-keep+ 
   :+bgfx-stencil-op-fail-s-mask+ 
   :+bgfx-stencil-op-fail-s-replace+ 
   :+bgfx-stencil-op-fail-s-shift+ 
   :+bgfx-stencil-op-fail-s-zero+ 
   :+bgfx-stencil-op-fail-z-decr+ 
   :+bgfx-stencil-op-fail-z-decrsat+ 
   :+bgfx-stencil-op-fail-z-incr+ 
   :+bgfx-stencil-op-fail-z-incrsat+ 
   :+bgfx-stencil-op-fail-z-invert+ 
   :+bgfx-stencil-op-fail-z-keep+ 
   :+bgfx-stencil-op-fail-z-mask+ 
   :+bgfx-stencil-op-fail-z-replace+ 
   :+bgfx-stencil-op-fail-z-shift+ 
   :+bgfx-stencil-op-fail-z-zero+ 
   :+bgfx-stencil-op-pass-z-decr+ 
   :+bgfx-stencil-op-pass-z-decrsat+ 
   :+bgfx-stencil-op-pass-z-incr+ 
   :+bgfx-stencil-op-pass-z-incrsat+ 
   :+bgfx-stencil-op-pass-z-invert+ 
   :+bgfx-stencil-op-pass-z-keep+ 
   :+bgfx-stencil-op-pass-z-mask+ 
   :+bgfx-stencil-op-pass-z-replace+ 
   :+bgfx-stencil-op-pass-z-shift+ 
   :+bgfx-stencil-op-pass-z-zero+ 
   :+bgfx-stencil-test-always+ 
   :+bgfx-stencil-test-equal+ 
   :+bgfx-stencil-test-gequal+ 
   :+bgfx-stencil-test-greater+ 
   :+bgfx-stencil-test-lequal+ 
   :+bgfx-stencil-test-less+ 
   :+bgfx-stencil-test-mask+ 
   :+bgfx-stencil-test-never+ 
   :+bgfx-stencil-test-notequal+ 
   :+bgfx-stencil-test-shift+ 
   :+bgfx-submit-eye-first+ 
   :+bgfx-submit-eye-left+ 
   :+bgfx-submit-eye-mask+ 
   :+bgfx-submit-eye-right+ 
   :+bgfx-submit-reserved-mask+ 
   :+bgfx-submit-reserved-shift+ 
   :+bgfx-texture-blit-dst+ 
   :+bgfx-texture-border-color-mask+ 
   :+bgfx-texture-border-color-shift+ 
   :+bgfx-texture-compare-always+ 
   :+bgfx-texture-compare-equal+ 
   :+bgfx-texture-compare-gequal+ 
   :+bgfx-texture-compare-greater+ 
   :+bgfx-texture-compare-lequal+ 
   :+bgfx-texture-compare-less+ 
   :+bgfx-texture-compare-mask+ 
   :+bgfx-texture-compare-never+ 
   :+bgfx-texture-compare-notequal+ 
   :+bgfx-texture-compare-shift+ 
   :+bgfx-texture-compute-write+ 
   :+bgfx-texture-mag-anisotropic+ 
   :+bgfx-texture-mag-mask+ 
   :+bgfx-texture-mag-point+ 
   :+bgfx-texture-mag-shift+ 
   :+bgfx-texture-min-anisotropic+ 
   :+bgfx-texture-min-mask+ 
   :+bgfx-texture-min-point+ 
   :+bgfx-texture-min-shift+ 
   :+bgfx-texture-mip-mask+ 
   :+bgfx-texture-mip-point+ 
   :+bgfx-texture-mip-shift+ 
   :+bgfx-texture-msaa-sample+ 
   :+bgfx-texture-none+ 
   :+bgfx-texture-read-back+ 
   :+bgfx-texture-reserved-mask+ 
   :+bgfx-texture-reserved-shift+ 
   :+bgfx-texture-rt+ 
   :+bgfx-texture-rt-mask+ 
   :+bgfx-texture-rt-msaa-mask+ 
   :+bgfx-texture-rt-msaa-shift+ 
   :+bgfx-texture-rt-msaa-x16+ 
   :+bgfx-texture-rt-msaa-x2+ 
   :+bgfx-texture-rt-msaa-x4+ 
   :+bgfx-texture-rt-msaa-x8+ 
   :+bgfx-texture-rt-write-only+ 
   :+bgfx-texture-sampler-bits-mask+ 
   :+bgfx-texture-srgb+ 
   :+bgfx-texture-u-border+ 
   :+bgfx-texture-u-clamp+ 
   :+bgfx-texture-u-mask+ 
   :+bgfx-texture-u-mirror+ 
   :+bgfx-texture-u-shift+ 
   :+bgfx-texture-v-border+ 
   :+bgfx-texture-v-clamp+ 
   :+bgfx-texture-v-mask+ 
   :+bgfx-texture-v-mirror+ 
   :+bgfx-texture-v-shift+ 
   :+bgfx-texture-w-border+ 
   :+bgfx-texture-w-clamp+ 
   :+bgfx-texture-w-mask+ 
   :+bgfx-texture-w-mirror+ 
   :+bgfx-texture-w-shift+ 
   :+bgfx-view-none+ 
   :+bgfx-view-stereo+ 
   :bgfx-access 
   :bgfx-alloc 
   :bgfx-alloc-instance-data-buffers 
   :bgfx-alloc-transform 
   :bgfx-alloc-transient-buffers 
   :bgfx-alloc-transient-index-buffer 
   :bgfx-alloc-transient-vertex-buffer 
   :bgfx-allocator-interface 
   :bgfx-allocator-interface-tclass 
   :bgfx-allocator-vtbl 
   :bgfx-allocator-vtbl-tclass 
   :bgfx-attachment 
   :bgfx-attachment-tclass 
   :bgfx-attrib 
   :bgfx-attrib-type 
   :bgfx-backbuffer-ratio 
   :bgfx-begin 
   :bgfx-blit 
   :bgfx-calc-texture-size 
   :bgfx-callback-interface 
   :bgfx-callback-interface-tclass 
   :bgfx-callback-vtbl 
   :bgfx-callback-vtbl-tclass 
   :bgfx-caps 
   :bgfx-caps-gpu 
   :bgfx-caps-gpu-tclass 
   :bgfx-caps-limits 
   :bgfx-caps-limits-tclass 
   :bgfx-caps-tclass 
   :bgfx-copy 
   :bgfx-create-compute-program 
   :bgfx-create-dynamic-index-buffer 
   :bgfx-create-dynamic-index-buffer-mem 
   :bgfx-create-dynamic-vertex-buffer 
   :bgfx-create-dynamic-vertex-buffer-mem 
   :bgfx-create-frame-buffer 
   :bgfx-create-frame-buffer-from-attachment 
   :bgfx-create-frame-buffer-from-handles 
   :bgfx-create-frame-buffer-from-nwh 
   :bgfx-create-frame-buffer-scaled 
   :bgfx-create-index-buffer 
   :bgfx-create-indirect-buffer 
   :bgfx-create-occlusion-query 
   :bgfx-create-program 
   :bgfx-create-shader 
   :bgfx-create-texture 
   :bgfx-create-texture-2d 
   :bgfx-create-texture-2d-scaled 
   :bgfx-create-texture-3d 
   :bgfx-create-texture-cube 
   :bgfx-create-uniform 
   :bgfx-create-vertex-buffer 
   :bgfx-dbg-text-clear 
   :bgfx-dbg-text-image 
   :bgfx-dbg-text-printf 
   :bgfx-dbg-text-vprintf 
   :bgfx-destroy-dynamic-index-buffer 
   :bgfx-destroy-dynamic-vertex-buffer 
   :bgfx-destroy-frame-buffer 
   :bgfx-destroy-index-buffer 
   :bgfx-destroy-indirect-buffer 
   :bgfx-destroy-occlusion-query 
   :bgfx-destroy-program 
   :bgfx-destroy-shader 
   :bgfx-destroy-texture 
   :bgfx-destroy-uniform 
   :bgfx-destroy-vertex-buffer 
   :bgfx-discard 
   :bgfx-dispatch 
   :bgfx-dispatch-indirect 
   :bgfx-dynamic-index-buffer-handle 
   :bgfx-dynamic-vertex-buffer-handle 
   :bgfx-encoder-alloc-transform 
   :bgfx-encoder-blit 
   :bgfx-encoder-discard 
   :bgfx-encoder-dispatch 
   :bgfx-encoder-dispatch-indirect 
   :bgfx-encoder-set-compute-dynamic-index-buffer 
   :bgfx-encoder-set-compute-dynamic-vertex-buffer 
   :bgfx-encoder-set-compute-index-buffer 
   :bgfx-encoder-set-compute-indirect-buffer 
   :bgfx-encoder-set-compute-vertex-buffer 
   :bgfx-encoder-set-condition 
   :bgfx-encoder-set-dynamic-index-buffer 
   :bgfx-encoder-set-dynamic-vertex-buffer 
   :bgfx-encoder-set-image 
   :bgfx-encoder-set-index-buffer 
   :bgfx-encoder-set-instance-data-buffer 
   :bgfx-encoder-set-instance-data-from-dynamic-vertex-buffer 
   :bgfx-encoder-set-instance-data-from-vertex-buffer 
   :bgfx-encoder-set-marker 
   :bgfx-encoder-set-scissor 
   :bgfx-encoder-set-scissor-cached 
   :bgfx-encoder-set-state 
   :bgfx-encoder-set-stencil 
   :bgfx-encoder-set-texture 
   :bgfx-encoder-set-transform 
   :bgfx-encoder-set-transform-cached 
   :bgfx-encoder-set-transient-index-buffer 
   :bgfx-encoder-set-transient-vertex-buffer 
   :bgfx-encoder-set-uniform 
   :bgfx-encoder-set-vertex-buffer 
   :bgfx-encoder-set-vertex-count 
   :bgfx-encoder-stats 
   :bgfx-encoder-stats-tclass 
   :bgfx-encoder-submit 
   :bgfx-encoder-submit-indirect 
   :bgfx-encoder-submit-occlusion-query 
   :bgfx-encoder-touch 
   :bgfx-end 
   :bgfx-fatal 
   :bgfx-frame 
   :bgfx-frame-buffer-handle 
   :bgfx-get-avail-instance-data-buffer 
   :bgfx-get-avail-transient-index-buffer 
   :bgfx-get-avail-transient-vertex-buffer 
   :bgfx-get-caps 
   :bgfx-get-internal-data 
   :bgfx-get-renderer-name 
   :bgfx-get-renderer-type 
   :bgfx-get-result 
   :bgfx-get-shader-uniforms 
   :bgfx-get-stats 
   :bgfx-get-supported-renderers 
   :bgfx-get-texture 
   :bgfx-get-uniform-info 
   :bgfx-handle 
   :bgfx-index-buffer-handle 
   :bgfx-indirect-buffer-handle 
   :bgfx-init 
   :bgfx-init-ctor 
   :bgfx-init-limits 
   :bgfx-init-limits-tclass 
   :bgfx-init-s 
   :bgfx-init-s-tclass 
   :bgfx-instance-data-buffer 
   :bgfx-instance-data-buffer-tclass 
   :bgfx-internal-data 
   :bgfx-internal-data-tclass 
   :bgfx-is-texture-valid 
   :bgfx-make-ref 
   :bgfx-make-ref-release 
   :bgfx-memory 
   :bgfx-memory-tclass 
   :bgfx-occlusion-query-handle 
   :bgfx-occlusion-query-result 
   :bgfx-override-internal-texture 
   :bgfx-override-internal-texture-ptr 
   :bgfx-platform-data 
   :bgfx-platform-data-tclass 
   :bgfx-program-handle 
   :bgfx-read-texture 
   :bgfx-release-fn 
   :bgfx-render-frame 
   :bgfx-renderer-type 
   :bgfx-request-screen-shot 
   :bgfx-reset 
   :bgfx-reset-view 
   :bgfx-resolution 
   :bgfx-resolution-tclass 
   :bgfx-set-compute-dynamic-index-buffer 
   :bgfx-set-compute-dynamic-vertex-buffer 
   :bgfx-set-compute-index-buffer 
   :bgfx-set-compute-indirect-buffer 
   :bgfx-set-compute-vertex-buffer 
   :bgfx-set-condition 
   :bgfx-set-debug 
   :bgfx-set-dynamic-index-buffer 
   :bgfx-set-dynamic-vertex-buffer 
   :bgfx-set-hwnd 
   :bgfx-set-image 
   :bgfx-set-index-buffer 
   :bgfx-set-instance-data-buffer 
   :bgfx-set-instance-data-from-dynamic-vertex-buffer 
   :bgfx-set-instance-data-from-vertex-buffer 
   :bgfx-set-marker 
   :bgfx-set-palette-color 
   :bgfx-set-platform-data 
   :bgfx-set-scissor 
   :bgfx-set-scissor-cached 
   :bgfx-set-shader-name 
   :bgfx-set-state 
   :bgfx-set-stencil 
   :bgfx-set-texture 
   :bgfx-set-texture-name 
   :bgfx-set-transform 
   :bgfx-set-transform-cached 
   :bgfx-set-transient-index-buffer 
   :bgfx-set-transient-vertex-buffer 
   :bgfx-set-uniform 
   :bgfx-set-vertex-buffer 
   :bgfx-set-vertex-count 
   :bgfx-set-view-clear 
   :bgfx-set-view-clear-mrt 
   :bgfx-set-view-frame-buffer 
   :bgfx-set-view-mode 
   :bgfx-set-view-name 
   :bgfx-set-view-order 
   :bgfx-set-view-rect 
   :bgfx-set-view-rect-auto 
   :bgfx-set-view-scissor 
   :bgfx-set-view-transform 
   :bgfx-set-view-transform-stereo 
   :bgfx-shader-handle 
   :bgfx-shutdown 
   :bgfx-stats 
   :bgfx-stats-tclass 
   :bgfx-submit 
   :bgfx-submit-indirect 
   :bgfx-submit-occlusion-query 
   :bgfx-text-clear 
   :bgfx-texture-format 
   :bgfx-texture-handle 
   :bgfx-texture-info 
   :bgfx-texture-info-tclass 
   :bgfx-topolog-sort-tri-list 
   :bgfx-topology 
   :bgfx-topology-convert 
   :bgfx-topology-sort 
   :bgfx-touch 
   :bgfx-transform 
   :bgfx-transform-tclass 
   :bgfx-transient-index-buffer 
   :bgfx-transient-index-buffer-tclass 
   :bgfx-transient-vertex-buffer 
   :bgfx-transient-vertex-buffer-tclass 
   :bgfx-uniform-handle 
   :bgfx-uniform-info 
   :bgfx-uniform-info-tclass 
   :bgfx-uniform-type 
   :bgfx-update-dynamic-index-buffer 
   :bgfx-update-dynamic-vertex-buffer 
   :bgfx-update-texture-2d 
   :bgfx-update-texture-3d 
   :bgfx-update-texture-cube 
   :bgfx-vertex-buffer-handle 
   :bgfx-vertex-convert 
   :bgfx-vertex-decl 
   :bgfx-vertex-decl-add 
   :bgfx-vertex-decl-begin 
   :bgfx-vertex-decl-decode 
   :bgfx-vertex-decl-end 
   :bgfx-vertex-decl-handle 
   :bgfx-vertex-decl-has 
   :bgfx-vertex-decl-skip 
   :bgfx-vertex-decl-tclass 
   :bgfx-vertex-pack 
   :bgfx-vertex-unpack 
   :bgfx-view-id 
   :bgfx-view-mode 
   :bgfx-view-stats 
   :bgfx-view-stats-tclass 
   :bgfx-weld-vertices))
